-- queries to create tables

-- Customers Table
CREATE TABLE Customers (
    CustomerID INT PRIMARY KEY,
    Name VARCHAR(100),
    Email VARCHAR(100),
    JoinDate DATE,
    City VARCHAR(50)
);

-- Restaurants Table
CREATE TABLE Restaurants (
    RestaurantID INT PRIMARY KEY,
    Name VARCHAR(100),
    Cuisine VARCHAR(50),
    City VARCHAR(50),
    Rating DECIMAL(3, 2)
);

-- Dishes Table
CREATE TABLE Dishes (
    DishID INT PRIMARY KEY,
    Name VARCHAR(100),
    RestaurantID INT,
    Price DECIMAL(10, 2),
    FOREIGN KEY (RestaurantID) REFERENCES Restaurants(RestaurantID)
);

-- Orders Table
CREATE TABLE Orders (
    OrderID INT PRIMARY KEY,
    CustomerID INT,
    RestaurantID INT,
    OrderDate DATE,
    TotalAmount DECIMAL(10, 2),
    FOREIGN KEY (CustomerID) REFERENCES Customers(CustomerID),
    FOREIGN KEY (RestaurantID) REFERENCES Restaurants(RestaurantID)
);

-- Deliveries Table
CREATE TABLE Deliveries (
    DeliveryID INT PRIMARY KEY,
    OrderID INT,
    DeliveryPerson VARCHAR(100),
    DeliveryTime INT, -- Delivery time in minutes
    FOREIGN KEY (OrderID) REFERENCES Orders(OrderID)
);

-- Reviews Table
CREATE TABLE Reviews (
    ReviewID INT PRIMARY KEY,
    CustomerID INT,
    OrderID INT,
    Rating INT CHECK (Rating BETWEEN 1 AND 5),
    ReviewText TEXT,
    ReviewDate DATE,
    FOREIGN KEY (CustomerID) REFERENCES Customers(CustomerID),
    FOREIGN KEY (OrderID) REFERENCES Orders(OrderID)
);

-- queries to insert table 

-- Customers Data
INSERT INTO Customers (CustomerID, Name, Email, JoinDate, City) VALUES
(1, 'Alice Johnson', 'alice@example.com', '2022-01-15', 'New York'),
(2, 'Bob Smith', 'bob@example.com', '2022-03-10', 'Los Angeles'),
(3, 'Charlie Brown', 'charlie@example.com', '2023-02-05', 'Chicago');

-- Restaurants Data
INSERT INTO Restaurants (RestaurantID, Name, Cuisine, City, Rating) VALUES
(1, 'Pizza Palace', 'Italian', 'New York', 4.5),
(2, 'Sushi Central', 'Japanese', 'Los Angeles', 4.8),
(3, 'Taco Town', 'Mexican', 'Chicago', 4.2);

-- Dishes Data
INSERT INTO Dishes (DishID, Name, RestaurantID, Price) VALUES
(1, 'Margherita Pizza', 1, 12.99),
(2, 'Pepperoni Pizza', 1, 14.99),
(3, 'Sushi Platter', 2, 22.99),
(4, 'Taco Combo', 3, 9.99);

-- Orders Data
INSERT INTO Orders (OrderID, CustomerID, RestaurantID, OrderDate, TotalAmount) VALUES
(1, 1, 1, '2023-10-10', 27.98),
(2, 2, 2, '2023-10-11', 22.99),
(3, 3, 3, '2023-10-12', 19.98);

-- Deliveries Data
INSERT INTO Deliveries (DeliveryID, OrderID, DeliveryPerson, DeliveryTime) VALUES
(1, 1, 'John Doe', 30),
(2, 2, 'Jane Smith', 25),
(3, 3, 'Carlos Gonzalez', 40);

-- Reviews Data
INSERT INTO Reviews (ReviewID, CustomerID, OrderID, Rating, ReviewText, ReviewDate) VALUES
(1, 1, 1, 5, 'Excellent pizza and quick delivery!', '2023-10-11'),
(2, 2, 2, 4, 'Great sushi, but delivery was a bit late.', '2023-10-12'),
(3, 3, 3, 3, 'Tacos were okay, delivery took too long.', '2023-10-13');


-- query execution 
-- Basic Queries
--     1. Retrieve the list of all dishes along with their restaurant names and prices.
    
    
    select DishID ,Dishes.Name as Dish_name,Restaurants.Name as Restaurant_name, Price from Restaurants
    JOIN Dishes
    ON Restaurants.RestaurantID = Dishes.RestaurantID ;
    
    
    -- 2. Find the average rating of all restaurants in New York.
    
    -- Inserted some more values to validate output 
    insert into Restaurants Values (4,"Joia do mar" ,"goan" ,"New York" ,"1");

    Select City , AVG(Rating) from Restaurants group by CIty  HAVING City = "New York";
    
    
    -- Intermediate Queries
    -- 3. Calculate the total revenue generated by each restaurant.

-- USING JOINS 
    select Restaurants.RestaurantID,  Restaurants.Name ,SUM(TotalAmount) as revenue
    FROM Restaurants 
    JOIN Orders 
    ON Orders.RestaurantID= Restaurants.RestaurantID 
    group by RestaurantID , Restaurants.Name
    order by revenue desc;

-- USING SUB query 

    select Name, RestaurantID ,(select SUM(TotalAmount) from Orders
    Where Orders.RestaurantID = Restaurants.RestaurantID) 
    AS TOTAL 
    FROM Restaurants;

    -- 4. List the names of customers who have ordered more than once.
    SELECT Name ,  COUNT(OrderID) as Orders_Count  
    FROM Orders Join Customers ON  Customers.CustomerID = Orders.CustomerID 
    group by Name , Customers.CustomerID HAVING Orders_Count > 1;


    -- Advanced Queries with Window Functions

    -- 5. Use a window function to rank restaurants based on their average customer ratings.
    Select RestaurantID , Cuisine , City  , Rating , 
    rank() over(order by Rating DESC) 
    from Restaurants;


    -- 6. Calculate the cumulative total revenue for each restaurant.
   
    SELECT Orders.RestaurantID, Restaurants.Name, Orders.TotalAmount,SUM(TotalAmount) 
    OVER (ORDER BY TotalAmount) AS Commulativetotal
    FROM Orders
    JOIN Restaurants 
    ON Orders.RestaurantID = Restaurants.RestaurantID;


    -- 7. Identify the top 2 most ordered dishes in each city using a window function.
    
    -- SOLVING USING WINDOW function

    SELECT *
    FROM (
    SELECT
        r.City,
        d.Name AS DishName,
        SUM(o.TotalAmount / d.Price) AS EstimatedDishQty,
        ROW_NUMBER() OVER (
            PARTITION BY r.City
            ORDER BY SUM(o.TotalAmount / d.Price) DESC
        ) AS r
    FROM Orders o
    JOIN Restaurants r ON o.RestaurantID = r.RestaurantID
    JOIN Dishes d ON d.RestaurantID = r.RestaurantID
    WHERE ABS(MOD(o.TotalAmount, d.Price)) < 0.01
    GROUP BY r.City, d.Name
    ) ranked
    WHERE r <= 2;
    
    -- SOLVING THE SAME WITHOUT WINDOW FUNCTION 
    SELECT 
    DishID, 
    Dishes.Name, 
    City, 
    COUNT(*) AS EstimateOrders, 
    SUM(Orders.TotalAmount / Dishes.Price) AS EstimateQty
    FROM Dishes
    JOIN Orders ON Dishes.RestaurantID = Orders.RestaurantID
    JOIN Restaurants ON Restaurants.RestaurantID = Orders.RestaurantID
    WHERE MOD(TotalAmount, Dishes.Price) = 0
    GROUP BY DishID, Dishes.Name, City
    HAVING (
    SELECT COUNT(*) 
    FROM (
        SELECT 
        d2.DishID, 
        SUM(o2.TotalAmount / d2.Price) AS EstQty
        FROM Dishes d2
        JOIN Orders o2 ON d2.RestaurantID = o2.RestaurantID
        JOIN Restaurants r2 ON r2.RestaurantID = o2.RestaurantID
        WHERE MOD(o2.TotalAmount, d2.Price) = 0
        AND r2.City = Restaurants.City
        GROUP BY d2.DishID
        HAVING SUM(o2.TotalAmount / d2.Price) > SUM(Orders.TotalAmount / Dishes.Price)
    ) AS HigherRanked
    ) < 2
    ORDER BY City, EstimateQty DESC;





    -- 8. Find the average delivery time for each delivery person and rank them.
   
    select  DeliveryID,OrderID,DeliveryPerson,AVG(DeliveryTime) 
    AS AvgTime , RANK() OVER(ORDER BY DeliveryTime DESC) as RANKS 
    from Deliveries 
    group by DeliveryID, OrderID , DeliveryPerson;

    -- Aggregations and Grouping
    -- 9. Retrieve the count of orders placed in each city.
    select City , COUNT(OrderID) 
    FROM Orders 
    JOIN Restaurants ON Restaurants.RestaurantID = Orders.RestaurantID 
    GROUP BY City ;




    -- 10. Calculate the average order value for each cuisine type.
    Select Cuisine , AVG(TotalAmount) 
    from Orders 
    JOIN Restaurants ON Restaurants.RestaurantID = Orders.RestaurantID 
    Group by Cuisine ;




    -- 11. List all reviews with a rating below 4.
    
    select * from Reviews where Rating<4;


    -- 12. Display all orders placed after October 1, 2023.
    
    select * from Orders where OrderDate>'2023-10-1';
    -- Joins

    -- 13. Write a query to display order details along with the restaurant and customer names.
    
    select Customers.Name as CustomerName , Restaurants.Name 
    as RestaurantNames , OrderID , OrderDate, TotalAmount 
    from Orders JOIN Customers 
    ON Customers.CustomerID = Orders.CustomerID 
    JOIN Restaurants 
    ON Restaurants.RestaurantID = Orders.RestaurantID ;

    -- 14. Show all dishes ordered by each customer.
    SELECT c.Name AS CustomerName, d.Name AS DishName
    FROM Orders o
    JOIN Restaurants r ON o.RestaurantID = r.RestaurantID
    JOIN Dishes d ON d.RestaurantID = r.RestaurantID
    JOIN Customers c ON c.CustomerID = o.CustomerID
    WHERE MOD(o.TotalAmount, d.Price) < 0.01;



    -- Subqueries

    --     15. Find the name of the customer who gave the lowest rating.

    select Customers.Name , Rating 
    from Customers 
    JOIN Reviews 
    ON Reviews.CustomerID = Customers.CustomerID 
    order by Rating Limit 1;

    --     16. Retrieve the most expensive dish for each cuisine type.
    Select * 
    from (
        select DishID,
        Dishes.Name,
        Cuisine,
        ROW_NUMBER() OVER( PARTITION BY Cuisine Order BY Price) AS roll 
        from Dishes join Restaurants ON Dishes.RestaurantID = Restaurants.RestaurantID
    )ranked 
    where roll<2;

    -- Analytical Queries

    --     17. Identify the delivery person with the fastest average delivery time.
    SELECT DeliveryPerson, AVG(DeliveryTime) AS Avg from Deliveries
    GROUP BY DeliveryPerson
    ORDER BY Avg ASC
    LIMIT 1;


    --     18. Calculate the average delivery time for all orders handled by "Carlos Gonzalez."
    select AVG(DeliveryTime) 
    from Deliveries 
    where DeliveryPerson ="Carlos Gonzalez";

    --     19. Use a window function to assign a rank to each review based on its date, grouped by customer.

    select ReviewID , Customers.Name as customer_name ,  Rating , ReviewText , 
    RANK() OVER(PARTITION BY Customers.CustomerID ORDER BY ReviewDate) AS ranks from Reviews 
    JOIN Customers ON Customers.CustomerID = Reviews.CustomerID;

    -- Advanced Window Functions

    --     20. Calculate the running total of revenue for orders by each customer.
    


    SELECT Customers.Name, Customers.CustomerID, Orders.OrderDate, Orders.TotalAmount,
    SUM(TotalAmount) OVER(PARTITION BY Customers.CustomerID 
    ORDER BY Orders.OrderDate) AS Running
    FROM Orders 
    JOIN Customers ON Customers.CustomerID = Orders.CustomerID;
